CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_stats (
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  games_played INTEGER DEFAULT 0,
  total_clicks INTEGER DEFAULT 0,
  best_score INTEGER DEFAULT 0,
  PRIMARY KEY (user_id)
);